### ISSUE TITLE
Improve naming of various envelope and message types.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/infix#132]
These types are reasonably confusing. I think it's acceptable that different packages have their own notion of an "envelope" with increasingly specific meta-data, but I don't like that there are multiple things called "Message", I would like to keep that meaning the `dogma.Message` specifically.

To that end:

- Rename `eventstore.Event` to `Envelope`, and rename `Envelope` field to `Proto`.
- Rename `queuestore.Message` to `Envelope`, and rename `Envelope` field to `Proto`.
- Move `pipeline.RecordedEvent` to `eventstore.EnvelopePair`
- Move `pipeline.EnqueuedMessage` to `queuestore.EnvelopePair`
- Change `queue.elem` to use `queuestore.EnvelopePair`

**Edit:** Also, if we can think of a better name that `Memory` for the "regular" envelope, that would be good.  It's all in-memory!

**Comment by jmalloc** [comment]
The result of these changes would give us something like the following for the queue, for example:

```
package queuestore

type Envelope struct {
	Revision      Revision
	FailureCount  uint
	NextAttemptAt time.Time
	Proto      *envelopespec.Envelope
}

type EnvelopePair struct {
	Memory    *envelope.Envelope
	Persisted *Envelope
}
```

@danilvpetrov, @koden-km -- what do you guys think of these names... specifically `EnvelopePair` to refer to the pair of in-memory and persisted envelope representations.

**Comment by jmalloc** [comment]
The two types not shown above are:

- [`envelope.Envelope`](https://github.com/dogmatiq/infix/blob/master/envelope/envelope.go#L8), the in-memory envelope that's passed around through most of the engine
- [`envelopespec.Envelope`](https://github.com/dogmatiq/infix/blob/master/draftspecs/envelopespec/envelope.proto#L57), the protocol buffers representation of an envelope. In the future this package will be external to the `dogmatiq/infix` repo

**Comment by koden-km** [comment]
Are those fields named `Proto` because they are to protobuf object instance?

**Comment by jmalloc** [comment]
Yep

**Comment by jmalloc** [comment]
I think I may actually be able to get rid of the `envelope.Envelope` type altogether now, I'll conduct some experiments.

**Comment by jmalloc** [comment]
This is so very done now! see #152.
